name: Daily Stock Analysis
on:
  schedule:
    # 한국 시간(KST) 아침 13시에 실행하려면 UTC 시간으로는 0시로 설정해야 합니다.
    - cron: '0 04 * * *'

jobs:
  run_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python automation.py
